<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelAgencySystem.Database.Memory\TravelAgencySystem.Database.Memory.csproj" />
    <ProjectReference Include="..\TravelAgencySystem.DataModel\TravelAgencySystem.DataModel.csproj" />
  </ItemGroup>

</Project>
